---
  apiVersion: helm.integrations.flux.weave.works/v1alpha
  kind: FluxHelmRelease
  metadata:
    name: mongodb
    namespace: kube-system
    labels:
      chart: mongodb
  spec:
    chartGitPath: mongodb
    releaseName: kube-system-mongodb
    values:
      image: bitnami/mongodb:3.7.1-r1
      imagePullPolicy: IfNotPresent
            
