---
  apiVersion: helm.integrations.flux.weave.works/v1alpha
  kind: FluxHelmRelease
  metadata:
    name: mongodb
    namespace: default
    labels:
      chart: mongodb
  spec:
    chartGitPath: mongodb
    releaseName: mongodb-database
    values:
      - name: image
        value: bitnami/mongodb:3.7.1-r0
      - name: imagePullPolicy
        value: IfNotPresent
      - name: resources.requests.cpu
        value: 99m
      - name: resources.requests.memory
        value: 500Mi
      - name: resources.requests.test
        value:  "[{\"A\":\"a\",\"B\":[\"n\",\"o\"]}]"
