---
apiVersion: helm.integrations.flux.weave.works/v1alpha
kind: FluxHelmRelease
metadata:
  name: nginx-ingress
  namespace: default
  labels:
    chart: nginx-ingress
spec:
  chartGitPath: nginx-ingress
  values:
  - name: controller.daemonset.useHostPorts
    value: "true"
  - name: controller.nodeSelector.pool_type
    value: lbe
  - name: controller.service.type
    value: ClusterIP
  - name: controller.stats.enabled
    value: "true"
  - name: nginx-ingress.controller.extraArgs.default-ssl-certificate
    value: nginx-ingress/default-ssl-certificate
